### ISSUE TITLE
hyperparameter tunning with AI Platform Training: issue with parameter dependency

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#37]
not possible to put in the .yaml file:
min_df<max_df

```
    params:
    - parameterName: WE_max_df
      type: DOUBLE
      minValue: 1.0
      maxValue: 1.0
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: WE_min_df
      type: DOUBLE
      minValue: 0
      maxValue: 0.3
      scaleType: UNIT_LINEAR_SCALE
```
